
Power Query M
--------------

DateTime.FromText("30 Dez 2010 02:04:50.369730", [Format="dd MMM yyyy HH:mm:ss.ffffff", Culture="de-DE"])

DateTime.FromText([EXECUTION_TIME], [Format="dd-MM-yy HH:mm:ss.fffff", Culture="fr-FR"])


Convert "2010-12-31T01:30:00" into a datetime value.

Copy
DateTime.FromText("2010-12-31T01:30:25")
Output

#datetime(2010, 12, 31, 1, 30, 25)

Example 2
Convert "2010-12-31T01:30:00.121212" into a datetime value.


Copy
DateTime.FromText("30 Dez 2010 02:04:50.369730", [Format="dd MMM yyyy HH:mm:ss.ffffff", Culture="de-DE"])
Output

#datetime(2010, 12, 30, 2, 4, 50.36973)

Example 3
Convert "2010-12-31T01:30:00" into a datetime value.

Copy
DateTime.FromText("2000-02-08T03:45:12Z", [Format="yyyy-MM-dd'T'HH:mm:ss'Z'", Culture="en-US"])
Output

#datetime(2000, 2, 8, 3, 45, 12)

Example 4
Convert "20101231T013000" into a datetime value.


Copy
DateTime.FromText("20101231T013000", [Format="yyyyMMdd'T'HHmmss", Culture="en-US"])
Output

#datetime(2010, 12, 31, 1, 30, 0)

--------------------------------------------

let
    Source = Excel.CurrentWorkbook(){[Name="Table1"]}[Content],
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Product ID", type text}, {"Category", type text}, {"Name", type text}, {"Size", type text}, {"Price", type number}, {"Units per pack", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Units per pack", "Units"}}),
    F= (x as number) as number =>
        let
            f=@F(x-1)+@F(x-2)
        in
            if(x=0 or x=1) then x else f,
    updatedColumns = Table.AddColumn(#"Renamed Columns", "Fibonacci", each F([Units]))
in
    updatedColumns
